WARMING UP EXERCISE: Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [1]:
import numpy as np

In [2]:
# TASK 1: Initialize an empty array with size 2X2.
empty_array = np.empty((2, 2))
print("Empty Array with size 2X2 :\n", empty_array)

Empty Array with size 2X2 :
 [[0.00000000e+000 1.34909358e-311]
 [1.34909358e-311 1.34909358e-311]]


In [3]:
# TASK 2: Initialize an all one array with size 4X2.
ones_array = np.ones((4, 2))
print("All one array with size 4X2: \n", ones_array)

All one array with size 4X2: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
# TASK 3: Return a new array of given shape and type, filled with fill value.
# {Hint: np.full}
filled_array= np.full((2, 3), 5,dtype=int)  # integer type
print("2X3 Array filled with 5 :\n", filled_array)

2X3 Array filled with 5 :
 [[5 5 5]
 [5 5 5]]


In [5]:
# TASK 4: Return a new array of zeros with same shape and type as a given array.
# {Hint: np.zeros like}
given_array = np.full((2, 3), 5,dtype=int)
zeros_array = np.zeros_like(given_array)
print("Given Array: \n",given_array)
print("\n Array of zeros (same shape/type as given array):\n", zeros_array)

Given Array: 
 [[5 5 5]
 [5 5 5]]

 Array of zeros (same shape/type as given array):
 [[0 0 0]
 [0 0 0]]


In [6]:
# TASK 5: Return a new array of ones with same shape and type as a given array.
# {Hint: np.ones like}
given_array = np.full((2, 3), 5,dtype=int)
ones_array = np.ones_like(given_array)
print("Given Array: \n",given_array)
print("\n Array of zeros (same shape/type as given array):\n", ones_array)


Given Array: 
 [[5 5 5]
 [5 5 5]]

 Array of zeros (same shape/type as given array):
 [[1 1 1]
 [1 1 1]]


In [7]:
# TASK 6: For an existing list new_list = [1,2,3,4] convert to an numpy array.
# {Hint: np.array()}
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n Converted List to Numpy Array:\n", numpy_array)


 Converted List to Numpy Array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [8]:
# TASK 1: Create an array with values ranging from 10 to 49.
# {Hint:np.arrange()}.
array_range = np.arange(10, 50)
print("Array with values ranging from 10 to 49:\n", array_range)

Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
# TASK 2: Create a 3X3 matrix with values ranging from 0 to 8.
# {Hint:look for np.reshape()}
matrix = np.arange(9).reshape(3, 3)
print("3x3 matrix with values ranging from 0 to 8:\n", matrix)

3x3 matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# TASK 3: Create a 3X3 identity matrix.{Hint:np.eye()}
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# TASK 4: Create a random array of size 30 and find the mean of the array.
# {Hint:check for np.random.random() and array.mean() function}
random_array = np.random.random(30)
mean = random_array.mean()
print("Random array :\n", random_array)
print("Mean Of Array:", mean)

Random array :
 [0.33816777 0.49826221 0.8181105  0.39347739 0.68983758 0.31298309
 0.53114546 0.41798783 0.01086028 0.55902306 0.89485567 0.32090266
 0.98137305 0.08245068 0.24626167 0.46654663 0.95576829 0.73135148
 0.10526668 0.90531409 0.50641543 0.02858804 0.32016799 0.89630124
 0.2734412  0.53282823 0.99980389 0.68888561 0.05004337 0.87460589]
Mean Of Array: 0.5143675651550582


In [12]:
#TASK 5: Create a 10X10 array with random values and find the minimum and maximum values.
random_values_array = np.random.random((10, 10))
min_value = random_values_array.min()
max_value = random_values_array.max()
print("10x10 random array:\n", random_values_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

10x10 random array:
 [[0.45919061 0.09091741 0.13616652 0.37729696 0.88752722 0.15035641
  0.51204545 0.73495309 0.79040231 0.37724456]
 [0.07237036 0.40811641 0.08227117 0.83184983 0.79465341 0.35618491
  0.85366829 0.87964221 0.49674426 0.26130432]
 [0.72704119 0.99788213 0.85568114 0.58131706 0.59609522 0.34567096
  0.533914   0.69991181 0.45900245 0.50667879]
 [0.56254173 0.44508411 0.46482229 0.83911115 0.14665893 0.32214089
  0.84161668 0.05649634 0.18462037 0.24000223]
 [0.28047218 0.29408053 0.25597067 0.10733605 0.92873138 0.00604188
  0.58194157 0.24416873 0.31526356 0.37618495]
 [0.5211629  0.18927574 0.46358633 0.52988294 0.86112938 0.46338952
  0.29723434 0.66584334 0.03763599 0.41853594]
 [0.66988814 0.71863868 0.51128628 0.62110783 0.07742517 0.30927109
  0.98432274 0.11533064 0.36459547 0.0401737 ]
 [0.5692481  0.46746867 0.40678069 0.77251158 0.73999203 0.1932535
  0.53280945 0.06917279 0.86951053 0.52625358]
 [0.85897068 0.50007713 0.02034963 0.12176968 0.89060952 0.9

In [13]:
# TASK 6: Create a zero array of size 10 and replace 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero array with 5th element replaced by 1:\n", zero_array)

Zero array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
# TASK 7: Reverse an array arr = [1,2,0,0,4,0].
array = np.array([1, 2, 0, 0, 4, 0])
reversed_array = array[::-1]
print("Reversed array:\n", reversed_array)

Reversed array:
 [0 4 0 0 2 1]


In [15]:
# TASK 8: Create a 2d array with 1 on border and 0 inside.
array_with_border = np.ones((5, 5))
array_with_border[1:-1, 1:-1] = 0
print("2D array with 1 on the border and 0 inside:\n", array_with_border)

2D array with 1 on the border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
#TASK 9: Create a 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("CHeckboard pattern matrix:\n", checkerboard)

CHeckboard pattern matrix:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [17]:
# TASK 1: Add the two array.
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);

v = np.array([9,10])
w = np.array([11,12]);

addition_first = x + y
print("Addition of x and v:\n", addition_first)

addition_second = v + w
print("Addition of v and w:", addition_second)

Addition of x and v:
 [[ 6  8]
 [10 13]]
Addition of v and w: [20 22]


In [18]:
# TASK 2: Subtract the two array
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);

v = np.array([9,10])
w = np.array([11,12]);

subtraction_first = x - y
print("Subtraction of x and v:\n", subtraction_first)

subtraction_second = v - w
print("Subtraction of v and w:", subtraction_second)

Subtraction of x and v:
 [[-4 -4]
 [-4 -3]]
Subtraction of v and w: [-2 -2]


In [19]:
# TASK 3: Multiply the array with any integers of your choice.
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);

v = np.array([9,10])
w = np.array([11,12]);

multiplication1 = x * 5
print("Multiplication of x with 5:\n", multiplication1)
multiplication2 = y * 5
print("Multiplication of y with 5:\n", multiplication2)
multiplication3 = v * 5
print("Multiplication of v with 5:\n", multiplication3)
multiplication4 = w * 5
print("Multiplication of w with 5:\n", multiplication4)

Multiplication of x with 5:
 [[ 5 10]
 [15 25]]
Multiplication of y with 5:
 [[25 30]
 [35 40]]
Multiplication of v with 5:
 [45 50]
Multiplication of w with 5:
 [55 60]


In [20]:
# TASK 4: Find the square of each element of the array.
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);

v = np.array([9,10])
w = np.array([11,12]);

square_x = np.square(x)
print("Square of each element in x:\n", square_x)
square_y = np.square(y)
print("Square of each element in y:\n", square_y)
square_v = np.square(v)
print("Square of each element in v:\n", square_v)
square_w = np.square(w)
print("Square of each element in w:\n", square_w)

Square of each element in x:
 [[ 1  4]
 [ 9 25]]
Square of each element in y:
 [[25 36]
 [49 64]]
Square of each element in v:
 [ 81 100]
Square of each element in w:
 [121 144]


In [21]:
# TASK 5: Find the dot product between: v(and)w ; x(and)v ; x(and)y.
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);

v = np.array([9,10])
w = np.array([11,12]);


dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [22]:
# TASK 6: Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);

v = np.array([9,10])
w = np.array([11,12]);

xy_concatenated = np.concatenate((x, y))
vw_concatenated = np.vstack((v, w)).T

print("Concatenation of x and y along rows: \n")
print(xy_concatenated)

print("\n Concatenation of v and w along columns: \n")
print(vw_concatenated)


Concatenation of x and y along rows: 

[[1 2]
 [3 5]
 [5 6]
 [7 8]]

 Concatenation of v and w along columns: 

[[ 9 11]
 [10 12]]


In [23]:
# TASK 7: Concatenate x(and)v;
# if you get an error, observe and explain why did you get the error?
x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

try:
    result = np.concatenate((x, v))
    print("Concatenation result:")
    print(result)
except ValueError as e:
    print("Error encountered:")
    print(e)


Error encountered:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BT AT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [24]:

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Proving A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1 = \n", identity_matrix)

print("Is A * A^-1 approximately I?", np.allclose(identity_matrix, np.eye(2)))

# Proving: AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB = \n", AB)
print("BA = \n", BA)
print("Is AB equal to BA?", np.array_equal(AB, BA))

# Proving: (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)

print("Is (AB)^T equal to B^T * A^T?", np.allclose(AB_T, BT_AT))

# Solving the linear system using inverse methods

coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
const_vector = np.array([-1, -3, 9])

coeff_matrix_inv = np.linalg.inv(coeff_matrix)
solution = np.dot(coeff_matrix_inv, const_vector)
print("Solution using inverse method: X = ", solution)

solution_direct = np.linalg.solve(coeff_matrix, const_vector)
print("Solution using np.linalg.solve: X = ", solution_direct)

print("Are both solutions approximately equal?", np.allclose(solution, solution_direct))


A * A^-1 = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A * A^-1 approximately I? True
AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Is AB equal to BA? False
Is (AB)^T equal to B^T * A^T? True
Solution using inverse method: X =  [ 2.  1. -2.]
Solution using np.linalg.solve: X =  [ 2.  1. -2.]
Are both solutions approximately equal? True
